# GirlTHing AI Lab — Radionica 1
## NumPy, Pandas i osnove linearne algebre

Ovaj notebook je uvod u tri alata/koncepta koje ćemo koristiti tokom cijelog ML/Data Science bloka:

1. **NumPy** — rad s nizovima brojeva (osnova za skoro sve u ML-u)
2. **Linearna algebra** — brzi podsjetnik (vektori, matrice) — vjerovatno vam je poznato, samo vidimo kako se to radi u kodu
3. **Pandas** — rad s tabelarnim podacima (DataFrame) — ovo ćemo najviše koristiti


---

# Dio 1 — NumPy

Plan:

* Kreiranje nizova (arrays)
* Osnovna svojstva niza: `shape`, `ndim`, `dtype`
* Indeksiranje i slicing
* Višedimenzionalni nizovi
* Nasumično generisani nizovi
* Operacije element-po-element
    * Operacije poređenja
    * Logičke operacije i filtriranje
* Sumarizacione operacije i `axis`

In [4]:
import numpy as np

In [5]:
np

## Kreiranje nizova

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [16]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

### Prvo pogledajmo kakav niz imamo

Prije obrade podataka često želimo znati:

* koliko elemenata/dimenzija imamo,
* kakav je oblik niza,
* kojeg su tipa vrijednosti.

In [17]:
a.shape

(6,)

In [18]:
a.ndim

1

In [19]:
a.dtype

dtype('int64')

In [20]:
len(a)

6

In [21]:
a[2] = 10

In [22]:
a

array([ 1,  2, 10,  5,  7, 12])

### Šta ako pokušamo upisati element na poziciju koja ne postoji?

NumPy niz ima definisanu veličinu/oblik. Možemo mijenjati postojeće elemente, ali ne možemo samo dodijeliti vrijednost novom indeksu.

In [ ]:
a[6] = 13

Ako nam zaista treba novi element, možemo napraviti novi niz pomoću `np.append()`:

In [ ]:
a = np.append(a, 13)
a

### Indeksiranje i slicing

U Data Science-u često ne želimo samo jedan element nego dio niza.

In [ ]:
a[0]      # prvi element

In [ ]:
a[1:4]    # indeksi 1, 2 i 3

In [ ]:
a[:3]     # prva tri elementa

In [ ]:
np.arange(3, 10)

In [ ]:
np.linspace(0, 100, 11)

`arange` zadaje **korak**, dok `linspace` zadaje **koliko ravnomjerno raspoređenih tačaka želimo** između početne i krajnje vrijednosti.

<h3 style="color:red">ZADATAK BR. 1</h3>

- Kreiraj niz [5, 10, 15, 20, 25]. 
- Ispiši treći element. 
- Promijeni drugi element u 100.
- Iz istog niza izdvoji prva 3 elementa i zatim elemente od indeksa 1 do 3.

In [6]:
# Probaj sama:
niz = np.array([5,10,15,20,25])
niz[2]
niz[1] = 100
niz[:3]
niz[1:4]

array([100,  15,  20])

## Višedimenzionalni nizovi

In [7]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [9]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
n.shape

(3, 3)

In [11]:
n.ndim

2

Kod 2D niza prvi indeks označava **red**, a drugi **kolonu**.

In [12]:
n[0, :]   # prvi red

array([1, 2, 3])

In [13]:
n[:, 0]   # prva kolona

array([1, 4, 7])

In [14]:
n[0, 1] = 20

In [15]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [16]:
n[2] = [1, 1, 1]

In [17]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [18]:
n[:, 2] = [0, 1, 2]

In [19]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

<h3 style="color:red">ZADATAK BR. 2</h3>

- Napravi matricu [[10,20,30],[40,50,60],[70,80,90]]. Izdvoji drugi red i treću kolonu.

In [23]:
# Probaj sama:
m = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
m[:,2]

array([30, 60, 90])

## Nasumično generisani nizovi

In [28]:
n= np.random.seed(2)

100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [30]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [31]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Operacije element-po-element

In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
b = (10 + (a * 2)) ** 2 / 100

In [34]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [35]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Operacije poređenja

In [36]:
a

array([0, 1, 2, 3, 4])

In [37]:
a >= 2

array([False, False,  True,  True,  True])

In [38]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [39]:
a > b

array([False, False,  True,  True,  True])

Više uslova možemo kombinovati sa `&` (**I**) i `|` (**ILI**). Svaki uslov stavljamo u zagrade:

In [40]:
(a >= 1) & (a <= 3)

array([False,  True,  True,  True, False])

In [41]:
a[(a >= 1) & (a <= 3)]

array([1, 2, 3])

Logičko indeksiranje — izdvoji samo elemente koji zadovoljavaju uslov:

In [42]:
a[a > b]

array([2, 3, 4])

<h3 style="color:red">ZADATAK BR. 3</h3>

- Za a = np.array([1,2,3,4,5]) napravi novi niz gdje je svaki element pomnožen sa 10.

In [44]:
# Probaj sama:
a= np.array([1,2,3,4,5])
b = a * 10
b

array([10, 20, 30, 40, 50])

<h3 style="color:red">ZADATAK BR. 4</h3>

- Iz a = np.array([3,7,2,9,12,4]) izdvoji samo vrijednosti veće od 5. Dodatni zadatak izdvoji vrijednosti između 5 i 10.

In [46]:
# Probaj sama:
a = np.array([3,7,2,9,12,4])
a[a>5]
a[(a>5) & (a<10)]

array([7, 9])

## Sumarizacione operacije

Najčešće sumarizacione operacije daju jednu vrijednost koja opisuje cijeli niz:

In [47]:
a

array([ 3,  7,  2,  9, 12,  4])

In [48]:
a.sum()

np.int64(37)

In [49]:
a.mean()

np.float64(6.166666666666667)

In [50]:
a.min()

np.int64(2)

In [51]:
a.max()

np.int64(12)

In [52]:
a.std()   # standardna devijacija

np.float64(3.531603350069515)

Kod matrica možemo birati po kojoj osi računamo rezultat.

In [53]:
m = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
m

array([[10, 20, 30],
       [40, 50, 60]])

In [54]:
m.mean(axis=0)   # prosjek po kolonama

array([25., 35., 45.])

In [55]:
m.mean(axis=1)   # prosjek po redovima

array([20., 50.])

<h3 style="color:red">ZADATAK BR. 5</h3>

- Izračunaj min, max, mean i sum za niz [12,15,18,20,25].

In [60]:
# Probaj sama:
q = np.array([12,15,18,20,25])
q.min()
q.max()
q.mean()
q.sum()

np.int64(90)

# Dio 2 — Linearna algebra (brzi podsjetnik)

_Ovo vam je vjerovatno poznato od prije — cilj je vidjeti kako se vektorske i matrične operacije rade u NumPy-u, jer se koriste kod skoro svakog ML modela._

Plan:

* Operacije nad vektorima
* Množenje
    * Množenje vektor–vektor
    * Množenje matrica–vektor
    * Množenje matrica–matrica
* Operator `@` za matrično množenje
* Transponovanje matrice
* Jedinična matrica (identity)
* Inverzna matrica

## Operacije nad vektorima

In [61]:
u = np.array([2, 4, 5, 6])

In [62]:
2 * u

array([ 4,  8, 10, 12])

In [63]:
v = np.array([1, 0, 0, 2])

In [64]:
u + v

array([3, 4, 5, 8])

In [65]:
u * v

array([ 2,  0,  0, 12])

## Množenje

In [67]:
v.shape[0]

4

**Vektor · vektor** (skalarni proizvod) — napišimo ga prvo ručno, da se vidi šta se dešava:

In [68]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [69]:
vector_vector_multiplication(u, v)

np.float64(14.0)

NumPy ovo već ima ugrađeno (i puno brže):

In [70]:
u.dot(v)

np.int64(14)

In [74]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [72]:
U.shape

(3, 4)

**Matrica · vektor** — svaki red matrice pomnožimo (skalarno) sa vektorom:

In [ ]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [ ]:
matrix_vector_multiplication(U, v)

In [ ]:
U.dot(v)

In [5]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

**Matrica · matrica** — kombinacija prethodnog, kolonu po kolonu:

In [ ]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [ ]:
matrix_matrix_multiplication(U, V)

In [ ]:
U.dot(V)

### Operator `@`

U modernom Python/NumPy kodu operator `@` vrlo jasno označava matrično množenje:

In [75]:
u @ v

np.int64(14)

In [76]:
U @ v

array([14,  5,  5])

In [77]:
U @ V

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Transponovanje matrice

Transponovanje zamijeni redove i kolone:

In [78]:
U.T

array([[2, 1, 3],
       [4, 2, 1],
       [5, 1, 2],
       [6, 2, 1]])

## Jedinična matrica (identity)

Množenje bilo čega jediničnom matricom vraća isti rezultat (kao množenje brojem 1):

In [2]:
import numpy as np

In [8]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [7]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverzna matrica

In [82]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [83]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

Matrica pomnožena svojom inverznom matricom daje jediničnu matricu:

In [84]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Dio 3 — Pandas

Plan:

* DataFrame-ovi
* Kako podatke učitavamo iz CSV fajla
* Brza inspekcija podataka: `shape`, `columns`, `dtypes`, `info()`
* Series
* Indeks: `loc` i `iloc`
* Pristupanje elementima
* Operacije element-po-element
* Filtriranje
* Operacije nad tekstom (stringovima)
* Sumarizacione operacije
* Kategorijske vrijednosti: `value_counts()`
* Nedostajuće vrijednosti
* Grupisanje
* Dobijanje NumPy nizova iz DataFrame-a

In [11]:
import numpy as np
import pandas as pd

## DataFrame-ovi

DataFrame možemo napraviti od liste listi + posebne liste naziva kolona:

In [70]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [71]:
df = pd.DataFrame(data, columns=columns)

In [68]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

Ili — često praktičnije — od liste rječnika (dict), gdje su ključevi nazivi kolona:

In [17]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [18]:
df = pd.DataFrame(data)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

### Kako podaci obično ulaze u Pandas

U praksi DataFrame najčešće nećemo ručno unositi. Podatke ćemo učitavati iz CSV/Excel fajlova, baza ili API-ja.

Najčešći primjer za CSV je:

In [69]:
# Primjer za stvarni fajl:
#df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

### Prva inspekcija nepoznatog skupa podataka

Kada dobijemo novi dataset, prije analize želimo brzo saznati njegovu veličinu, kolone, tipove podataka i nedostajuće vrijednosti.

In [21]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

Shape: (2160, 12)
Columns: ['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage', 'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price']

In [22]:
df.dtypes

Laptop              str
Status              str
Brand               str
Model               str
CPU                 str
RAM               int64
Storage           int64
Storage type        str
GPU                 str
Screen          float64
Touch               str
Final Price     float64
dtype: object

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Laptop        2160 non-null   str
 1   Status        2160 non-null   str
 2   Brand         2160 non-null   str
 3   Model         2160 non-null   str
 4   CPU           2160 non-null   str
 5   RAM           2160 non-null   int64
 6   Storage       2160 non-null   int64
 7   Storage type  2118 non-null   str
 8   GPU           789 non-null    str
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   str
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), str(8)
memory usage: 202.6 KB

`head(n)` prikazuje samo prvih n redova — korisno kad je tabela velika:

In [24]:
df.head(n=2)

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.0
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.0

## Series

Jedna kolona DataFrame-a zove se **Series**. Postoje dva načina da je izdvojimo:

Pažnja — ovo neće raditi jer naziv kolone sadrži razmak (`Engine HP`), pa Python ne zna gdje prestaje naziv atributa:

In [25]:
df.Engine HP

SyntaxError: invalid syntax (1897567212.py, line 1)

Zato uvijek koristimo pristup preko srednjih zagrada — radi za bilo koji naziv kolone:

In [30]:
df['Status']

0               New
1               New
2               New
3               New
4               New
           ...
2155    Refurbished
2156    Refurbished
2157    Refurbished
2158    Refurbished
2159    Refurbished
Name: Status, Length: 2160, dtype: str

In [28]:
print(df.columns.tolist())

['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage', 'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price']

Više kolona odjednom — proslijedimo listu naziva:

In [31]:
df[['Laptop', 'Model', 'GPU']]

                                                 Laptop       Model       GPU
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...  ExpertBook       NaN
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          Go       NaN
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...  ExpertBook       NaN
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...      Katana  RTX 3050
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...         15S       NaN
...                                                 ...         ...       ...
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...       Blade  RTX 3060
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...       Blade  RTX 3070
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...       Blade  RTX 3080
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...        Book       NaN
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...        Book       NaN

[2160 rows x 3 columns]

Dodavanje nove kolone je jednostavno — samo joj dodijelimo listu vrijednosti:

In [32]:
df['id'] = [1, 2, 3, 4, 5]

ValueError: Length of values (5) does not match length of index (2160)

In [ ]:
df['id'] = [10, 20, 30, 40, 50]

In [33]:
df

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2155,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3060,17.3,No,2699.99
2156,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3070,17.3,No,2899.99
2157,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,32,1000,SSD,RTX 3080,17.3,No,3399.99
2158,Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...,Refurbished,Razer,Book,Intel Evo Core i7,16,1000,SSD,NaN,13.4,Yes,1899.99
2159,Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...,Refurbished,Razer,Book,Intel Evo Core i7,16,256,SSD,NaN,13.4,Yes,1699.99

Brisanje kolone:

In [ ]:
del df['id']

In [ ]:
df

## Indeks

Svaki DataFrame ima indeks — oznaku za svaki red (podrazumijevano su to brojevi 0, 1, 2...):

In [35]:
df.index

RangeIndex(start=0, stop=2160, step=1)

In [42]:
df.Status.index

RangeIndex(start=0, stop=2160, step=1)

Indeks možemo i sami postaviti:

In [38]:
df.index = ['a', 'b', 'c', 'd', 'e']

ValueError: Length mismatch: Expected axis has 2160 elements, new values have 5 elements

In [39]:
df

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2155,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3060,17.3,No,2699.99
2156,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3070,17.3,No,2899.99
2157,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,32,1000,SSD,RTX 3080,17.3,No,3399.99
2158,Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...,Refurbished,Razer,Book,Intel Evo Core i7,16,1000,SSD,NaN,13.4,Yes,1899.99
2159,Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...,Refurbished,Razer,Book,Intel Evo Core i7,16,256,SSD,NaN,13.4,Yes,1699.99

`iloc` bira redove po **poziciji**, bez obzira na indeks:

In [40]:
df.iloc[[1, 2, 4]]

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

`loc` bira redove prema **oznaci indeksa**, dok `iloc` bira prema **poziciji**:

In [41]:
df.loc[['b', 'c', 'e']]

KeyError: "None of [Index(['b', 'c', 'e'], dtype='str')] are in the [index]"

Vraćanje na podrazumijevani numerički indeks:

In [43]:
df = df.reset_index(drop=True)

In [44]:
df

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2155,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3060,17.3,No,2699.99
2156,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3070,17.3,No,2899.99
2157,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,32,1000,SSD,RTX 3080,17.3,No,3399.99
2158,Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...,Refurbished,Razer,Book,Intel Evo Core i7,16,1000,SSD,NaN,13.4,Yes,1899.99
2159,Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...,Refurbished,Razer,Book,Intel Evo Core i7,16,256,SSD,NaN,13.4,Yes,1699.99

## Operacije element-po-element

Isto kao kod NumPy nizova — operacija se primjenjuje na svaki element odjednom:

In [ ]:
df['Engine HP'] * 2

In [ ]:
df['Year'] >= 2015

## Filtriranje

Uslov (npr. `df['Year'] >= 2015`) vraća niz True/False vrijednosti — koristimo ga da izdvojimo samo redove koji zadovoljavaju uslov:

In [78]:
df[
    df['Make'] == 'Nissan'
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

Više uslova kombinujemo sa `&` (I) ili `|` (ILI) — svaki uslov mora biti u zagradama:

In [ ]:
df[
    (df['Make'] == 'Nissan') & (df['Year'] >= 2015)
]

## Operacije nad tekstom (stringovima)

Čisti Python string ima svoje metode:

In [45]:
'AI Lab Radionica 1'.replace(' ', '_')

'AI_Lab_Radionica_1'

In [49]:
print(df.columns.tolist())
df

['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage', 'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price']

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2155,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3060,17.3,No,2699.99
2156,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3070,17.3,No,2899.99
2157,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,32,1000,SSD,RTX 3080,17.3,No,3399.99
2158,Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...,Refurbished,Razer,Book,Intel Evo Core i7,16,1000,SSD,NaN,13.4,Yes,1899.99
2159,Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...,Refurbished,Razer,Book,Intel Evo Core i7,16,256,SSD,NaN,13.4,Yes,1699.99

Pandas ima iste metode, ali preko `.str`, pa se primjenjuju na cijelu kolonu odjednom:

In [50]:
df['Brand'].str.lower()

0         asus
1       alurin
2         asus
3          msi
4           hp
         ...
2155     razer
2156     razer
2157     razer
2158     razer
2159     razer
Name: Brand, Length: 2160, dtype: str

Metode se mogu ulančati (chain) — ovo mijenja kolonu trajno:

In [54]:
df['Laptop'] = df['Laptop'].str.replace(' ', '_').str.upper()

In [55]:
df

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS_EXPERTBOOK_B1_B1502CBA-EJ0436X_INTEL_CORE...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,ALURIN_GO_START_INTEL_CELERON_N4020/8GB/256GB_...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS_EXPERTBOOK_B1_B1502CBA-EJ0424X_INTEL_CORE...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI_KATANA_GF66_12UC-082XES_INTEL_CORE_I7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP_15S-FQ5085NS_INTEL_CORE_I5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2155,RAZER_BLADE_17_FHD_360HZ_INTEL_CORE_I7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3060,17.3,No,2699.99
2156,RAZER_BLADE_17_FHD_360HZ_INTEL_CORE_I7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3070,17.3,No,2899.99
2157,RAZER_BLADE_17_FHD_360HZ_INTEL_CORE_I7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,32,1000,SSD,RTX 3080,17.3,No,3399.99
2158,RAZER_BOOK_13_INTEL_EVO_CORE_I7-1165G7/16GB/1T...,Refurbished,Razer,Book,Intel Evo Core i7,16,1000,SSD,NaN,13.4,Yes,1899.99
2159,RAZER_BOOK_FHD+_INTEL_EVO_CORE_I7-1165G7/16GB/...,Refurbished,Razer,Book,Intel Evo Core i7,16,256,SSD,NaN,13.4,Yes,1699.99

## Sumarizacione operacije

`describe()` daje brzi statistički pregled svih brojčanih kolona

In [58]:
df.describe().round(2)

           RAM  Storage   Screen  Final Price
count  2160.00  2160.00  2156.00      2160.00
mean     15.41   596.29    15.17      1312.64
std       9.87   361.22     1.20       911.48
min       4.00     0.00    10.10       201.05
25%       8.00   256.00    14.00       661.08
50%      16.00   512.00    15.60      1031.95
75%      16.00  1000.00    15.60      1708.97
max     128.00  4000.00    18.00      7150.47

Koliko različitih (unikatnih) vrijednosti ima svaka kolona:

In [59]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

Za kategorijske kolone često želimo vidjeti **koje vrijednosti postoje i koliko puta se pojavljuju**:

In [61]:
df['Laptop'].value_counts()

Laptop
ASUS_EXPERTBOOK_B1_B1502CBA-EJ0436X_INTEL_CORE_I5-1235U/8GB/512GB_SSD/15.6"    1
ALURIN_GO_START_INTEL_CELERON_N4020/8GB/256GB_SSD/15.6"                        1
ASUS_EXPERTBOOK_B1_B1502CBA-EJ0424X_INTEL_CORE_I3-1215U/8GB/256GB_SSD/15.6"    1
MSI_KATANA_GF66_12UC-082XES_INTEL_CORE_I7-12700H/16GB/1TB_SSD/RTX3050/15.6"    1
HP_15S-FQ5085NS_INTEL_CORE_I5-1235U/16GB/512GB_SSD/15.6"                       1
                                                                              ..
RAZER_BLADE_17_FHD_360HZ_INTEL_CORE_I7-11800H/16GB/1TB_SSD/RTX_3060/17.3"      1
RAZER_BLADE_17_FHD_360HZ_INTEL_CORE_I7-11800H/16GB/1TB_SSD/RTX_3070/17.3"      1
RAZER_BLADE_17_FHD_360HZ_INTEL_CORE_I7-11800H/32GB/1TB_SSD/RTX_3080/17.3"      1
RAZER_BOOK_13_INTEL_EVO_CORE_I7-1165G7/16GB/1TB_SSD/13.4"_TÁCTIL               1
RAZER_BOOK_FHD+_INTEL_EVO_CORE_I7-1165G7/16GB/256GB_SSD/13.4"_TÁCTIL           1
Name: count, Length: 2160, dtype: int64

## Nedostajuće vrijednosti

Broj nedostajućih (NaN) vrijednosti po koloni

In [64]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

Samo otkriti nedostajuće vrijednosti nije dovoljno — moramo odlučiti šta s njima.

Jedna mogućnost je zamijeniti ih nulom:

In [ ]:
df['Engine HP'].fillna(0)

Druga mogućnost je, zavisno od problema, zamijeniti ih npr. prosječnom vrijednošću:

In [ ]:
df['Engine HP'].fillna(df['Engine HP'].mean())

## Grupisanje

Ako znate SQL, ovo vam je poznato — `groupby` u pandasu odgovara `GROUP BY` u SQL-u:

```
SELECT 
    transmission_type,
    AVG(MSRP)
FROM
    cars
GROUP BY
    transmission_type
```

U pandasu:

In [72]:
df.groupby('Transmission Type')['MSRP'].mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

<h3 style="color:red">ZADATAK BR. 6</h3>

Koristeći `df`:

1. pronađi sve Nissan automobile
2. pronađi samo automobile sa `MANUAL` mjenjačem,
3. izračunaj prosječnu cijenu (`MSRP`) po godini proizvodnje.

In [79]:
# Probaj sama:
df[df['Make']=='Nissan']

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [81]:
df[df['Transmission Type'] == 'MANUAL']

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [82]:
df.groupby('Year')['MSRP'].mean()

Year
1991     2000.000000
2010    54990.000000
2017    31313.333333
Name: MSRP, dtype: float64

## Dobijanje NumPy nizova iz DataFrame-a

Kad god zatreba, iz Series-a ili DataFrame-a možemo izvući "čisti" NumPy niz pomoću `to_numpy()`:

In [83]:
df['MSRP'].to_numpy()

array([ 2000, 27150, 54990, 34450, 32340])

Ili cijeli DataFrame kao listu rječnika (npr. za slanje kroz API, JSON, itd.):

In [84]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'MSRP': 32340}]

---

## Kraj — šta dalje

Ovo pokriva osnove NumPy-a i Pandasa koje ćemo koristiti tokom cijelog ML/Data Science bloka.

Važna veza koju ćemo stalno koristiti:

**Pandas DataFrame → čišćenje i izbor feature-a → NumPy nizovi/matrice → ML model**

Ne morate pamtiti svaku funkciju. Važnije je da prepoznate obrazac rada: **učitaj → pregledaj → očisti → filtriraj → transformiši → analiziraj/modeliraj**.